# Generated by Django 4.0.6 on 2022-07-30 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pay_day',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_out',
            field=models.CharField(max_length=2, verbose_name='Pagado'),
        ),
    ]
