# Generated by Django 4.0.6 on 2022-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_pay_day_alter_client_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pay_day',
            field=models.CharField(max_length=2, verbose_name='Fecha de pago'),
        ),
    ]
